### ISSUE TITLE
홑소리 'ㅏ'가 스펙문서와 다르게 동작합니다

### ISSUE THREAD

**Issue by kswgit** [aheui/avis#27]
## 홑소리 'ㅏ'가 스펙문서와 다르게 동작합니다
문서에 따르면 '다' 커서 처리 시 커서를 오른쪽으로 한 칸 옮겨야 하나,  다음  
소스코드에서 아희 스펙문서와 다르게 동작하는 것을 확인하였습니다.

## 소스코드
```
방빠빠빠삭방빠빠뿌
다망받밦다맣타뭉수
쏜ㅁㅁㅁㅁㅁㅁ붇쑨
속ㅁㅁㅁㅁㅁㅁ붒숙
쏜ㅁㅁㅁㅁㅁㅁ댜쑨맣따망받밦다맣나망받밦다맣라망희
소썬석썬서썬석썬서
```
## 기대한 동작
![기대 동작 사진](https://imgur.com/Pokbfgm.png)

## 실제 동작
![실제 동작 사진](https://imgur.com/6jxAQp4.png)

**Comment by disjukr** [comment]
위 코드에서 `다` 명령을 실행해야되는 시점에 선택되어있는 저장공간은 비어있는 `악` 스택이고, 다음의 스펙에 의해 커서의 방향은 진행방향의 반대로 꺾이게 됩니다:

http://aheui.github.io/specification.ko

> - 연산에 필요한 충분한 갯수의 값이 저장공간에 저장되어 있지 않은 경우, 커서는 그 명령을 실행하지 않고 진행해야 할 방향의 반대방향으로 움직입니다.
>   - 종료만 제외하고, 중복과 바꿔치기 명령을 포함한 모든 뽑아내기를 쓰는 명령에 해당합니다.

**Comment by kswgit** [comment]
앗...

감사합니다
